### ISSUE TITLE
Proof read by @jaspertandy

### ISSUE THREAD

**Issue by sveneisenschmidt** [sveneisenschmidt/yay#143]
Awesome @jaspertandy checked the documentation and made some suggestions to improve it.

---
https://github.com/sveneisenschmidt/yay

> Gamification done simple.

Should either be "gamification made simple" or "gamification done simply"

> The project originally started as a 36 hours 

36 hour

> ultimate goal to write your own and tailored integration

ultimate goal being to write...

> Want to try it out or develop it further, please

Want to try it out or develop it further? Please

> Yay, isn't that awesome!

Yay! Isn't that awesome?!

https://github.com/sveneisenschmidt/yay/blob/master/docs/getting-started.md

> and integrations to extend yay

Yay

> these will be provided through the `docker-compose` file during development

these will be provided through the `docker-compose.yml` file during development

> In product they need to be passed to the running container that includes the application or e.g. provided via SetEnv by a Apache2 web server

In production they need to be passed to the running container that includes the application. e.g. via SetEnv by an Apache2 web server

> An on-the-fly generated API documentation can be found under

Automatically-generated API documentation can be found at

https://github.com/sveneisenschmidt/yay/blob/master/docs/customisation.md

> and four possible children nodes

child nodes

> Validators validates a players actions against any achievement and grants if validation passed the validation

Wayyyy too many uses of "validation"! Try something like "prerequisites for obtaining an achievement"?

> achievement after certain set of actions have

after a certain set...

> achievement criteria are met

have been met

> and values on second level are the properties of the validator

On webhooks.incoming - looks like this might have been copy-pasted?

> processor by it's name through a route parameter

its

> Internally processors implement

Internally, processors implement

> Internally processors implement the ProcessorInterface interface for incoming webhooks and implement the ProcessorInterface interface for outgoing webhooks.

Internally, processors implement the ProcessorInterface for incoming and outgoing webhooks

> The following emails are send

sent

> Infamous git platform GitHub

Infamous means to be well-known for being bad - not sure if that's what you're trying to say!

https://github.com/sveneisenschmidt/yay/blob/master/docs/examples.md

> Yay's API supports filtering, sorting and paginating for `GET requests

Looks like missing a closing `?

> An on-the-fly generated API documentation can be found under

Same as before: "Automatically-generated API documentation can be found at"

> Value of field name does not equals Jane Doe

does not equal

> To run the demo we need to enable the demo integration, you can do so by using

To run the demo we need to enable the demo integration. You can do so by using

> No achievement were granted yet

No achievements were granted yet

> For this, perform four more times our demo.action action

For this, perform the demo.action action four more times

> Et voilà, we earned our first achievement!

Et voilà: we earned our first achievement!

> Now let us go further, Let the player perform five times more the demo-action-01 action.

Now let's go further. Let the player perform the demo-action-01 action five more times.

> Our player earned now his official second achievement

Our player earned their second official achievement

(switching pronoun to "their" since their called "Jane" and neutrality is best)

> Let's check now our player achievements by performing the following request

Let's check our player achievements...

https://github.com/sveneisenschmidt/yay/blob/master/docs/under-the-hood.md

> Webhooks are the super glue that connects the outside world with your Yay instance.

I'm not sure I like the super glue metaphor here! Maybe cables or similar are better?

> Processors implement the ProcessorInterface interface for incoming webhooks and implement the ProcessorInterface interface for outgoing webhooks.

Processors implement the ProcessorInterface interface for incoming and outgoing webhooks.

> The webhook implementation requires that after the processor or all processor via the

The webhook implementation requires that after the processor or all processors via the...

> you can follow the GitHub example to see all benefits of processing webhook payloads

you can follow the GitHub example to see all the benefits of processing webhook payloads

> Infamous git platform GitHub use the concept of webhooks

Infamous again. And "uses"

https://github.com/sveneisenschmidt/yay/blob/master/docs/contributing.md

> git clone git@github.com:sveneisenschmidt/yay.git yay

git clone git@github.com:sveneisenschmidt/yay.git will clone to `yay` by default - providing that directory is redundant

> To see all provided commands run make and a list of available target is rendered.

To see all provided commands run make and a list of available targets is rendered.

**Comment by jaspertandy** [comment]
Wow I used the wrong "their"! I never do that!

> since their called

since they're called...
