### ISSUE TITLE
Implement continous integration tools

### ISSUE THREAD

**Issue by sveneisenschmidt** [sveneisenschmidt/yay#3]
After every push the project needs to run against the tests via `make test`.  

- [x] StyleCI: Connect repository to StyleCI
- [ ] StyleCI: Fix reported issues
- [ ] Travis CI: Connect repository to Travis CI
- [ ] Travis CI: Make tests run against PHP 7.1, PHP 7.2 RC

**Comment by VictorAvelar** [comment]
Do you have acceptance criteria for this one?

**Comment by sveneisenschmidt** [comment]
@VictorAvelar I added some thoughts, any feedback or improvements?
